# Generated by Django 5.2.4 on 2025-09-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForayFungi2023',
            fields=[
                ('foray_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('genus_and_species_org_entry', models.TextField(blank=True, null=True)),
                ('genus_and_species_conf', models.TextField(blank=True, null=True)),
                ('genus_and_species_foray_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['foray_id'],
            },
        ),
        migrations.CreateModel(
            name='MycoBankList',
            fields=[
                ('mycobank_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('taxon_name', models.TextField(blank=True, null=True)),
                ('current_name', models.TextField(blank=True, null=True)),
                ('authors', models.TextField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('hyperlink', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['mycobank_id'],
            },
        ),
        migrations.CreateModel(
            name='ForayMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foray_id', models.CharField(db_index=True, max_length=100)),
                ('org_entry', models.CharField(max_length=255)),
                ('conf_name', models.CharField(max_length=255)),
                ('foray_name', models.CharField(max_length=255)),
                ('match_category', models.CharField(db_index=True, max_length=50)),
            ],
            options={
                'ordering': ['foray_id'],
                'indexes': [models.Index(fields=['foray_id'], name='core_foraym_foray_i_5bf54d_idx'), models.Index(fields=['match_category'], name='core_foraym_match_c_100aa8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ForayMismatchExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foray_id', models.CharField(db_index=True, max_length=100)),
                ('org_entry', models.CharField(max_length=255)),
                ('conf_name', models.CharField(max_length=255)),
                ('foray_name', models.CharField(max_length=255)),
                ('explanation', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'ordering': ['foray_id'],
                'indexes': [models.Index(fields=['foray_id'], name='core_foraym_foray_i_1ff88f_idx'), models.Index(fields=['explanation'], name='core_foraym_explana_291a38_idx')],
            },
        ),
        migrations.CreateModel(
            name='ForayMismatchMycoScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foray_id', models.CharField(db_index=True, max_length=100)),
                ('org_score', models.FloatField()),
                ('conf_score', models.FloatField()),
                ('foray_score', models.FloatField()),
                ('mycobank_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('mycobank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mycobank_expl', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'ordering': ['foray_id'],
                'indexes': [models.Index(fields=['foray_id'], name='core_foraym_foray_i_0bdfe9_idx'), models.Index(fields=['mycobank_id'], name='core_foraym_mycoban_00d8be_idx')],
            },
        ),
        migrations.CreateModel(
            name='ForayPerfectMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foray_id', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['foray_id'],
                'indexes': [models.Index(fields=['foray_id'], name='core_forayp_foray_i_8be333_idx')],
            },
        ),
        migrations.CreateModel(
            name='ForayPerfectMycoMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foray_id', models.CharField(db_index=True, max_length=100)),
                ('matched_name', models.CharField(max_length=255)),
                ('mycobank_id', models.CharField(db_index=True, max_length=100)),
                ('mycobank_name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['foray_id'],
                'indexes': [models.Index(fields=['foray_id'], name='core_forayp_foray_i_3145ab_idx'), models.Index(fields=['mycobank_id'], name='core_forayp_mycoban_8cf3c3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReviewedMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foray_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('org_entry', models.CharField(blank=True, max_length=255, null=True)),
                ('conf_name', models.CharField(blank=True, max_length=255, null=True)),
                ('foray_name', models.CharField(blank=True, max_length=255, null=True)),
                ('validated_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reviewer_name', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('REVIEWED', 'Reviewed'), ('PENDING', 'Pending'), ('SKIPPED', 'Skipped')], default='REVIEWED', max_length=10)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-reviewed_at'],
                'indexes': [models.Index(fields=['status'], name='core_review_status_a5a161_idx'), models.Index(fields=['reviewed_at'], name='core_review_reviewe_8d1c22_idx')],
            },
        ),
    ]
